version: '3.9'

services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.local
    command: npm run dev
    depends_on:
      - convex

  convex:
    build: .
    ports:
      - "8787:8787"
    volumes:
      - .:/app
      - /app/node_modules
      
    env_file:
      - .env.local
    command: npx convex dev
