import type { Metadata } from 'next'
import './globals.css'
import ConvexClerkProvider from '@/providers/ConvexClerkProvider'
import Navbar from '@/components/models/Navbar'
import { ThemeProvider } from '@/providers/ThemeProvider'
import { RedirectToSignIn, SignedIn, SignedOut } from "@clerk/nextjs"
import { Toaster } from 'react-hot-toast'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ConvexClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SignedIn>
              <div className="min-h-screen">
                <Navbar />
                <main className="px-4 sm:px-6 lg:px-8">{children}</main>
              </div>
            </SignedIn>
            <SignedOut>
              <RedirectToSignIn />
            </SignedOut>
          </ThemeProvider>
          <Toaster/>
        </body>
      </html>
    </ConvexClerkProvider>
  )
}
